### ISSUE TITLE
approle

### ISSUE THREAD

**Issue by juev** [rumyantseva/app-with-vault#1]
Авторизация по токену? Почему не approle?
И передавать токен через энвы не безопасно же?

**Comment by rumyantseva** [comment]
Т.е. тебя не смутило, что Vault в Docker-compose развернут и хранилище in memory? :D 
Авторизация не через токен, а через то, что задано в переменных окружения. Это просто учебный пример для локальной работы, не production-ready.

**Comment by rumyantseva** [comment]
Если что, п

**Comment by juev** [comment]
Если только для примера. Сам просто недавно столкнулся с тем, что в реальной работе подобные примеры пользы никакой не несут. 

В случае кубернетес используется система авторизации на основе jwt токенов и авторизации на уровне кубер-волт.

**Comment by juev** [comment]
Если мой вопрос прозвучал грубо, прошу прощения. Ни в коем разе не хотел обидеть.

Просто учебные примеры должны базироваться на реальных кейсах. Ведь так?
